name: Versioning

on:
  pull_request:
    types: [closed]
    branches: [main]

permissions:
  id-token: write
  contents: write
  pull-requests: read
  issues: read
  statuses: write

jobs:
  Bump-Version:
    name: SemVer Label Processor
    if:  ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-ecosystem/action-release-label@v1
        id: version-label
        with:
          label_prefix: version-

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: ${{ steps.version-label.outputs.level || 'patch' }}

      - uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ steps.bump-semver.outputs.new_version }}
          message: '${{ steps.bump-semver.outputs.new_version }}: PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}'
